### ISSUE TITLE
ValueError: Circular reference detected

### ISSUE THREAD

**Issue by agusmakmun** [marselester/json-log-formatter#23]
For somehow, I have this error:

```bash
WARNING 2021-12-19 19:39:37,079 log 33 140073058801408 Forbidden (Referer checking failed - no Referer.): /
django_1        | --- Logging error ---
django_1        | Traceback (most recent call last):
django_1        |   File "/usr/local/lib/python3.8/logging/handlers.py", line 69, in emit
django_1        |     if self.shouldRollover(record):
django_1        |   File "/usr/local/lib/python3.8/logging/handlers.py", line 185, in shouldRollover
django_1        |     msg = "%s\n" % self.format(record)
django_1        |   File "/usr/local/lib/python3.8/logging/__init__.py", line 925, in format
django_1        |     return fmt.format(record)
django_1        |   File "/usr/local/lib/python3.8/site-packages/json_log_formatter/__init__.py", line 71, in format
django_1        |     return self.to_json(mutated_record)
django_1        |   File "/usr/local/lib/python3.8/site-packages/json_log_formatter/__init__.py", line 84, in to_json
django_1        |     return self.json_lib.dumps(record, default=_json_serializable)
django_1        |   File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
django_1        |     return cls(
django_1        |   File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
django_1        |     chunks = self.iterencode(o, _one_shot=True)
django_1        |   File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
django_1        |     return _iterencode(o, 0)
django_1        | ValueError: Circular reference detected
```

Meanwhile, I have a reference to solve that issue: https://stackoverflow.com/a/68035331/6396981
Can you please resolve this issue?

**Comment by marselester** [comment]
If you have a chance, please let me know if this change solves your problem https://github.com/marselester/json-log-formatter/pull/24.

**Comment by agusmakmun** [comment]
@marselester that's should be enough I guess.
can you please release it into new tag?

fast response, thank you 👍

**Comment by marselester** [comment]
You're welcome! Here you go https://pypi.org/project/JSON-log-formatter/0.5.0/.
